version: "3.8"

services:
  db:
    container_name: go_mysql
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - 3306:3306
#    volumes:
#      - go_data:/var/lib/mysql:rw
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345678
      - MYSQL_DATABASE=test_db
      - MYSQL_ROOT_PASSWORD=12345678
    tty: true
    networks:
      - go_network

  go_starter:
    container_name: go_starter
    build:
      context: .
    ports:
      - 8080:8080
    command: serve
    environment:
      - APP_PORT=8080
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=12345678
      - DB_NAME=test_db
      - ACCESS_TOKEN_SECRET=access_token_secret
      - REFRESH_TOKEN_SECRET=refresh_token_secret
      - ACCESS_TOKEN_EXPIRY=3000
      - REFRESH_TOKEN_EXPIRY=10080
      - CONTEXT_KEY=auth
    tty: true
    depends_on:
      - db
    networks:
      - go_network
    restart: on-failure:3


networks:
  go_network:
    name: go_network
    driver: bridge

volumes:
  go_data:
    name: go_data